### ISSUE TITLE
Change in upstream private conda API for subdir_data

### ISSUE THREAD

**Issue by costrouc** [conda/conda-libmamba-solver#118]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Original bug is detailed here by @jaimergp in https://github.com/conda/conda-libmamba-solver/pull/111#issuecomment-1398227594 second bullet point. It broke due to this upstream change in conda see https://github.com/conda/conda/commit/f474462658ef6e3763c1193db0f8edbea01fa5fe#diff-ff8022ba5d08310acbbc6f95e1bc77a53f69e00ffe6daa51026af8880f89612dR452. This error showed up in the following github action https://github.com/conda/conda-libmamba-solver/actions/runs/3996526735/jobs/6856696067. With the following traceback.

```python
Traceback (most recent call last):
  File "/home/test_user/.local/lib/python3.10/site-packages/conda_libmamba_solver/index.py", line 163, in _fetch_channel_url_with_conda
    subdir_data.load()
  File "/opt/conda-src/conda/core/subdir_data.py", line 215, in load
    _internal_state = self._load()
  File "/opt/conda-src/conda/core/subdir_data.py", line 359, in _load
    _internal_state = self._process_raw_repodata_str(raw_repodata_str, mod_etag_headers)
TypeError: _DownloadOnlySubdirData._process_raw_repodata_str() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda-src/tests/gateways/test_connection.py", line 102, in test_s3_server
    with make_temp_env(
  File "/opt/conda/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/conda-src/conda/testing/integration.py", line 326, in make_temp_env
    run_command(Commands.CREATE, prefix, *packages, **kwargs)
  File "/opt/conda-src/conda/testing/integration.py", line 287, in run_command
    result = do_call(args, p)
  File "/opt/conda-src/conda/cli/conda_argparse.py", line 91, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/conda-src/conda/notices/core.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda-src/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/opt/conda-src/conda/cli/install.py", line 264, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/opt/conda-src/conda/core/solve.py", line 131, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/opt/conda-src/conda/core/solve.py", line 174, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/test_user/.local/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 167, in solve_final_state
    index = LibMambaIndexHelper(
  File "/home/test_user/.local/lib/python3.10/site-packages/conda_libmamba_solver/index.py", line 71, in __init__
    self._index = self._load_channels()
  File "/home/test_user/.local/lib/python3.10/site-packages/conda_libmamba_solver/index.py", line 260, in _load_channels
    full_index.append(self._fetch_channel_url_with_conda(url))
  File "/home/test_user/.local/lib/python3.10/site-packages/conda_libmamba_solver/index.py", line 172, in _fetch_channel_url_with_conda
    subdir_data.load()
  File "/opt/conda-src/conda/core/subdir_data.py", line 215, in load
    _internal_state = self._load()
  File "/opt/conda-src/conda/core/subdir_data.py", line 359, in _load
    _internal_state = self._process_raw_repodata_str(raw_repodata_str, mod_etag_headers)
TypeError: _DownloadOnlySubdirData._process_raw_repodata_str() takes 2 positional arguments but 3 were given
---------------------------- Captured stdout setup -----------------------------
Starting mock_s3_server
/opt/conda-src/.pytest_cache/d/.xprocess/minio_s3_server$ /usr/local/bin/minio server --address=:9000 /home/test_user/pytesttmp/test_s3_server0
process 'minio_s3_server' started pid=2842
Formatting 1st pool, 1 set(s), 1 drives per set.

WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.

WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables

MinIO Object Storage Server

minio_s3_server process startup detected
Server (PID: 2842) log file can be found here: /opt/conda-src/.pytest_cache/d/.xprocess/minio_s3_server/xprocess.log
````

cc @jaimergp 

### Conda Info

```shell
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/test_user/.condarc
 populated config files : 
          conda version : 23.1.0.post13+f9c3afeaf
    conda-build version : 3.23.3
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=6.0.7=0
                          __unix=0=0
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/test_user/.conda/pkgs
       envs directories : /home/test_user/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/23.1.0.post13+f9c3afeaf requests/2.28.1 CPython/3.9.16 Linux/6.0.7 debian/11 glibc/2.31
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
empty
```

### Conda list

```shell
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
anaconda-client           1.11.0           py39h06a4308_0    defaults
attrs                     22.1.0           py39h06a4308_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.11.1           py39h06a4308_0    defaults
boto3                     1.24.28          py39h06a4308_0    defaults
botocore                  1.27.59          py39h06a4308_0    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.18.1               h7f8727e_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7        py39h06a4308_0    defaults
cffi                      1.15.1           py39h5eee18b_3    defaults
cfgv                      3.3.1            py39h06a4308_0    defaults
chardet                   4.0.0           py39h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4            py39h06a4308_0    defaults
clyent                    1.2.2            py39h06a4308_1    defaults
conda                     23.1.0.post13+f9c3afeaf           dev_0    <develop>
conda-build               3.23.3           py39h06a4308_0    defaults
conda-content-trust       0.1.3            py39h06a4308_0    defaults
conda-libmamba-solver     22.8.1                   pypi_0    pypi
conda-package-handling    2.0.2            py39h06a4308_0    defaults
conda-package-streaming   0.7.0            py39h06a4308_0    defaults
conda-verify              3.4.2                      py_1    defaults
coverage                  6.3.2            py39h7f8727e_0    defaults
cryptography              38.0.4           py39h9ce1e76_0    defaults
curl                      7.87.0               h5eee18b_0    defaults
distlib                   0.3.6            py39h06a4308_0    defaults
docutils                  0.18.1           py39h06a4308_3    defaults
execnet                   1.9.0              pyhd3eb1b0_0    defaults
expat                     2.4.9                h6a678d5_0    defaults
filelock                  3.9.0            py39h06a4308_0    defaults
flake8                    6.0.0            py39h06a4308_0    defaults
flit                      3.6.0              pyhd3eb1b0_0    defaults
flit-core                 3.6.0              pyhd3eb1b0_0    defaults
fmt                       8.1.1                hd09550d_1    defaults
future                    0.18.2           py39h06a4308_1    defaults
gdbm                      1.18                 hd4cb3f1_4    defaults
gettext                   0.21.0               hf68c758_0    defaults
git                       2.34.1          pl5262hc120c5b_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 he6710b0_3    defaults
identify                  2.5.5            py39h06a4308_0    defaults
idna                      3.4              py39h06a4308_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
jinja2                    2.11.3             pyhd8ed1ab_2    conda-forge
jmespath                  0.10.0             pyhd3eb1b0_0    defaults
jsonschema                4.16.0           py39h06a4308_0    defaults
jupyter_core              5.1.1            py39h06a4308_0    defaults
krb5                      1.19.4               h568e23c_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                hab531cd_0    defaults
libcurl                   7.87.0               h91b91d3_0    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
liblief                   0.12.3               h6a678d5_0    defaults
libmamba                  1.0.0                ha06983f_0    defaults
libmambapy                1.0.0            py39ha06983f_0    defaults
libnghttp2                1.46.0               hce63b2e_0    defaults
libsolv                   0.7.22               he621ea3_0    defaults
libssh2                   1.10.0               h8f2d780_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libxml2                   2.9.14               h74e7548_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.0.1            py39h27cfd23_0    defaults
mccabe                    0.7.0              pyhd3eb1b0_0    defaults
nbformat                  5.7.0            py39h06a4308_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
nodeenv                   1.7.0            py39h06a4308_0    defaults
openssl                   1.1.1s               h7f8727e_0    defaults
packaging                 22.0             py39h06a4308_0    defaults
patch                     2.7.6             h7b6447c_1001    defaults
patchelf                  0.15.0               h6a678d5_0    defaults
pcre2                     10.37                he7ceb23_1    defaults
perl                      5.34.0               h5eee18b_2    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pip                       22.3.1           py39h06a4308_0    defaults
pkginfo                   1.8.3            py39h06a4308_0    defaults
platformdirs              2.5.2            py39h06a4308_0    defaults
pluggy                    1.0.0            py39h06a4308_1    defaults
pre-commit                3.0.1            py39hf3d152e_0    conda-forge
psutil                    5.9.0            py39h5eee18b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
py                        1.11.0             pyhd3eb1b0_0    defaults
py-lief                   0.12.3           py39h6a678d5_0    defaults
pybind11-abi              4                    hd3eb1b0_0    defaults
pycodestyle               2.10.0           py39h06a4308_0    defaults
pycosat                   0.6.4            py39h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pycrypto                  2.6.1           py39h27cfd23_10    defaults
pyflakes                  3.0.1            py39h06a4308_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyrsistent                0.18.0           py39heee7806_0    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
pytest                    7.1.2            py39h06a4308_0    defaults
pytest-cov                3.0.0              pyhd3eb1b0_0    defaults
pytest-forked             1.3.0              pyhd3eb1b0_0    defaults
pytest-mock               3.10.0           py39h06a4308_0    defaults
pytest-rerunfailures      10.1               pyhd3eb1b0_0    defaults
pytest-split              0.8.0              pyhd8ed1ab_0    conda-forge
pytest-timeout            1.4.2                      py_0    defaults
pytest-xdist              2.5.0              pyhd3eb1b0_0    defaults
pytest-xprocess           0.22.2             pyhd8ed1ab_0    conda-forge
python                    3.9.16               h7a1cb2a_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2           py39h06a4308_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.7           py39h06a4308_0    defaults
pyyaml                    6.0              py39h5eee18b_1    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.28.1           py39h06a4308_0    defaults
responses                 0.13.3             pyhd3eb1b0_0    defaults
ripgrep                   13.0.0               hbdeaff8_0    defaults
ruamel.yaml               0.17.21          py39h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6            py39h5eee18b_1    defaults
s3transfer                0.6.0            py39h06a4308_0    defaults
setuptools                65.6.3           py39h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.3.2.post1      py39h06a4308_0    defaults
sqlite                    3.40.1               h5082296_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1            py39h06a4308_0    defaults
tomli-w                   1.0.0              pyhd3eb1b0_0    defaults
toolz                     0.12.0           py39h06a4308_0    defaults
tqdm                      4.64.1           py39h06a4308_0    defaults
traitlets                 5.7.1            py39h06a4308_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
ukkonen                   1.0.1            py39hdb19cb5_0    defaults
urllib3                   1.26.14          py39h06a4308_0    defaults
virtualenv                20.17.1          py39h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xdoctest                  1.1.0              pyhd8ed1ab_0    conda-forge
xz                        5.2.10               h5eee18b_1    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yaml-cpp                  0.7.0                h295c915_1    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.18.0           py39h5eee18b_0    defaults
zstd                      1.5.2                ha4553b6_0    defaults
```

### Additional Context

Testing all of this via the docker image in the docs/dev/setup.md.

**Comment by costrouc** [comment]
The new python class for SubdirData

```python
class SubdirData:
    def _read_local_repodata(self, state):
          ....
    def _process_raw_repodata_str(self, raw_repodata_str, state: dict | None = None):
         ....
    def _process_raw_repodata(self, repodata, state=None):
         ....
    def _pickle_me(self):
        ....
```

When we compare with what we have in conda-libmamba-solver.

````python
class SubdirData:
    def _read_local_repdata(self, etag, mod_stamp):
        return self._internal_state_template

    def _process_raw_repodata_str(self, raw_repodata_str):
        return self._internal_state_template

    def _process_raw_repodata(self, repodata):
        return self._internal_state_template

    def _pickle_me(self):
        return
```

**Comment by costrouc** [comment]
I've inspected the methods and looks like they preserve the same return values. We just need to modify the function api for conda-libmamba-solver's api. So the change looks easy. Currently I've been stuck on Friday and today on how to actually run the test. When I run

```shell
pytest tests/gateways/test_connection.py::test_s3_server
```

within the docker image I does not run properly. I think I need to figure out how to start the minio server for tests.

**Comment by costrouc** [comment]
Looks like the test fixture is failing for some reason running minio. Getting 
```shell
sudo bash ./dev/linux/setup.sh 
````

But now running into

```shell
Traceback (most recent call last):
  File "/opt/conda-src/tests/gateways/test_connection.py", line 82, in test_s3_server    minio_s3_server.populate_bucket(endpoint, bucket_name, channel_dir)
  File "/opt/conda-src/conda/testing/gateways/fixtures.py", line 81, in populate_bucket
    client.upload_file(
  File "/opt/conda/lib/python3.9/site-packages/boto3/s3/inject.py", line 143, in upload_file
    return transfer.upload_file(
  File "/opt/conda/lib/python3.9/site-packages/boto3/s3/transfer.py", line 294, in upload_file
    raise S3UploadFailedError(
boto3.exceptions.S3UploadFailedError: Failed to upload /opt/conda-src/tests/data/conda_format_repo/index.html to minio_s3_server/index.html: An error occurred (SlowDown) when calling the PutObject operation (reached max retries: 4): Resource requested is unreadable, please reduce your request rate

```
