### ISSUE TITLE
CondaValueError when default solver is set to libmamba and using the Conda CLI Python API

### ISSUE THREAD

**Issue by swainn** [conda/conda-libmamba-solver#202]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

# What happens?

Minimal Reproducible Case:

1. Update conda and install libmamba per instructions: https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community.
2. Set libmamba to be default solver:

```bash
conda config --set solver libmamba
```

3. Create new environment with conda installed (to be able to use Python API) and activate

```bash
conda create -n foo conda
conda activate foo
```

4. Create a `libmamba_issue.py` with the following contents:

```python
from conda.cli.python_api import run_command as conda_run, Commands


conda_run(
    Commands.INSTALL,
    ['-c', 'conda-forge', '--freeze-installed', 'pandas'],
    use_exception_handler=False,
    stdout=None,
    stderr=None,
)
```

5. Run script

```bash
python libmamba_issue.py
```

The following error is raised:

<details>

```
Traceback (most recent call last):
  File "/home/aquadev/tethys/scripts/conda_libmamba_issue.py", line 4, in <module>
    conda_run(
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/python_api.py", line 118, in run_command
    raise e
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/python_api.py", line 107, in run_command
    result = do_call(args, p)
             ^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
    return getattr(module, func_name)(args, parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/notices/core.py", line 121, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/install.py", line 248, in install
    solver_backend = context.plugin_manager.get_cached_solver_backend()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/manager.py", line 149, in get_solver_backend
    raise CondaValueError(
conda.exceptions.CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
```

</details>

# What should happen?

The pandas package should be installed using the Python API and the libmamba solver.

### Conda Info

```shell
<details>


    active environment : foo
    active env location : /home/aquadev/miniconda3/envs/foo
            shell level : 2
       user config file : /home/aquadev/.condarc
 populated config files : /home/aquadev/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.90.1=0
                          __unix=0=0
       base environment : /home/aquadev/miniconda3  (writable)
      conda av data dir : /home/aquadev/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aquadev/miniconda3/pkgs
                          /home/aquadev/.conda/pkgs
       envs directories : /home/aquadev/miniconda3/envs
                          /home/aquadev/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.10.11 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35 solver/libmamba conda-libmamba-solver/23.3.0 libmambapy/1.4.1
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>
```


### Conda Config

```shell
<details>


==> /home/aquadev/.condarc <==
solver: libmamba
```

</details>
```


### Conda list

```shell
<details>


# packages in environment at /home/aquadev/miniconda3/envs/foo:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
boltons                   23.0.0          py311h06a4308_0    defaults
brotlipy                  0.7.0           py311h5eee18b_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7       py311h06a4308_0    defaults
cffi                      1.15.1          py311h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.3.1          py311h06a4308_0    defaults
conda-package-handling    2.0.2           py311h06a4308_0    defaults
conda-package-streaming   0.7.0           py311h06a4308_0    defaults
cryptography              39.0.1          py311h9ce1e76_0    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   1.1.1t               h7f8727e_0    defaults
packaging                 23.0            py311h06a4308_0    defaults
pip                       23.0.1          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pycosat                   0.6.4           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.3               h7a1cb2a_0    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.29.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                66.0.0          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py311h06a4308_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.15         py311h06a4308_0    defaults
wheel                     0.38.4          py311h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
```

</details>
```


### Additional Context

* The same error is thrown in #185, but due to a different cause (CLI use vs CLI Python API use).
* This error does not occur when running the script in the base environment and the package is installed successfully.

**Comment by jaimergp** [comment]
You need `conda-libmamba-solver` in the same environment as `conda`. There's no other way to allow Python imports without some seriously ugly hacking :D 

Does the problem go away if you co-install conda-libmamba-solver in your "Python API" env?

**Comment by swainn** [comment]
@jaimergp of course, that makes sense. Why didn't I think to try that? It did install the package successfully. However, the following traceback in printed to the console when it starts:

<details>

```
Traceback (most recent call last):
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/virtual_packages/cuda.py", line 42, in cuda_version
    detector.start()
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/aquadev/tethys/scripts/conda_libmamba_issue.py", line 4, in <module>
    conda_run(
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/python_api.py", line 118, in run_command
    raise e
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/python_api.py", line 107, in run_command
    result = do_call(args, p)
             ^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
    return getattr(module, func_name)(args, parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/notices/core.py", line 121, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/cli/install.py", line 264, in install
    unlink_link_transaction = solver.solve_for_transaction(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/core/solve.py", line 177, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda_libmamba_solver/solver.py", line 135, in solve_final_state
    in_state = SolverInputState(
               ^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda_libmamba_solver/state.py", line 189, in __init__
    _supplement_index_with_system(virtual)
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/core/index.py", line 170, in _supplement_index_with_system
    packages = context.plugin_manager.get_hook_results("virtual_packages")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/manager.py", line 100, in get_hook_results
    plugins = sorted(
              ^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/manager.py", line 101, in <genexpr>
    (item for items in hook() for item in items),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/virtual_packages/cuda.py", line 65, in conda_virtual_packages
    cuda_version = cached_cuda_version()
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/virtual_packages/cuda.py", line 60, in cached_cuda_version
    return cuda_version()
           ^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/common/decorators.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/site-packages/conda/plugins/virtual_packages/cuda.py", line 46, in cuda_version
    detector.kill()  # requires Python 3.7+
    ^^^^^^^^^^^^^^^
  File "/home/aquadev/miniconda3/envs/foo/lib/python3.11/multiprocessing/process.py", line 140, in kill
    self._popen.kill()
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'kill'
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/aquadev/miniconda3/envs/foo

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           2 KB  conda-forge
    blas-1.0                   |              mkl           1 KB  conda-forge
    bottleneck-1.3.5           |  py311hbed6279_0         133 KB
    ca-certificates-2023.5.7   |       hbcca054_0         145 KB  conda-forge
    certifi-2023.5.7           |     pyhd8ed1ab_0         149 KB  conda-forge
    conda-23.3.1               |  py311h38be061_0         1.2 MB  conda-forge
    intel-openmp-2023.1.0      |   hdb19cb5_46305        17.1 MB
    mkl-2023.1.0               |   h6d00ec8_46342       171.5 MB
    mkl-service-2.4.0          |  py311h5eee18b_1          54 KB
    mkl_fft-1.3.6              |  py311ha02d727_1         217 KB
    mkl_random-1.2.2           |  py311ha02d727_1         291 KB
    numexpr-2.8.4              |  py311h65dcdc2_1         161 KB
    numpy-1.24.3               |  py311h08b1b3b_1          11 KB
    numpy-base-1.24.3          |  py311hf175353_1         7.2 MB
    pandas-1.5.3               |  py311hba01205_0        12.9 MB
    python-dateutil-2.8.2      |     pyhd8ed1ab_0         240 KB  conda-forge
    python_abi-3.11            |          2_cp311           5 KB  conda-forge
    pytz-2023.3                |     pyhd8ed1ab_0         182 KB  conda-forge
    six-1.16.0                 |     pyh6c4a22f_0          14 KB  conda-forge
    tbb-2021.5.0               |       h924138e_1         1.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       213.4 MB

The following NEW packages will be INSTALLED:

  blas               conda-forge/linux-64::blas-1.0-mkl 
  bottleneck         pkgs/main/linux-64::bottleneck-1.3.5-py311hbed6279_0 
  intel-openmp       pkgs/main/linux-64::intel-openmp-2023.1.0-hdb19cb5_46305 
  mkl                pkgs/main/linux-64::mkl-2023.1.0-h6d00ec8_46342 
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py311h5eee18b_1 
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.6-py311ha02d727_1 
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py311ha02d727_1 
  numexpr            pkgs/main/linux-64::numexpr-2.8.4-py311h65dcdc2_1 
  numpy              pkgs/main/linux-64::numpy-1.24.3-py311h08b1b3b_1 
  numpy-base         pkgs/main/linux-64::numpy-base-1.24.3-py311hf175353_1 
  pandas             pkgs/main/linux-64::pandas-1.5.3-py311hba01205_0 
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0 
  python_abi         conda-forge/linux-64::python_abi-3.11-2_cp311 
  pytz               conda-forge/noarch::pytz-2023.3-pyhd8ed1ab_0 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
  tbb                conda-forge/linux-64::tbb-2021.5.0-h924138e_1 

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2023.01.10~ --> conda-forge::ca-certificates-2023.5.7-hbcca054_0 
  certifi            pkgs/main/linux-64::certifi-2022.12.7~ --> conda-forge/noarch::certifi-2023.5.7-pyhd8ed1ab_0 

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex                                   pkgs/main --> conda-forge 
  conda              pkgs/main::conda-23.3.1-py311h06a4308~ --> conda-forge::conda-23.3.1-py311h38be061_0 



Downloading and Extracting Packages
                                                                                                                        
Preparing transaction: done                                                                                             
Verifying transaction: done                                                                                             
Executing transaction: done 
```

</details>

It still works, but is a little disconcerting.
