### ISSUE TITLE
Installing mamba from fresh conda docker image broken libarchive (defaults -> conda-forge)

### ISSUE THREAD

**Issue by costrouc** [conda/conda-libmamba-solver#297]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Adding this as a bug (which it may not be?) but this seems too easy to run into.

```
docker run -it continuumio/miniconda3
$ conda install -c conda-forge mamba
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.5.2
  latest version: 23.7.4

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.4



## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - mamba


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |       2_kmp_llvm           6 KB  conda-forge
    ca-certificates-2023.7.22  |       hbcca054_0         146 KB  conda-forge
    certifi-2023.7.22          |     pyhd8ed1ab_0         150 KB  conda-forge
    conda-23.7.4               |  py311h38be061_0         1.3 MB  conda-forge
    fmt-10.1.1                 |       h00ab1b0_0         188 KB  conda-forge
    libcurl-8.2.1              |       h251f7ec_0         399 KB
    libgcc-ng-13.2.0           |       h807b86a_2         753 KB  conda-forge
    libmamba-1.5.1             |       h744094f_0         1.6 MB  conda-forge
    libmambapy-1.5.1           |  py311hf2555c7_0         293 KB  conda-forge
    libsolv-0.7.24             |       hfc55251_4         457 KB  conda-forge
    libstdcxx-ng-13.2.0        |       h7e041cc_2         3.7 MB  conda-forge
    libzlib-1.2.13             |       hd590300_5          60 KB  conda-forge
    llvm-openmp-16.0.6         |       h4dfa4b3_0        39.9 MB  conda-forge
    mamba-1.5.1                |  py311h3072747_0          64 KB  conda-forge
    openssl-3.1.3              |       hd590300_0         2.5 MB  conda-forge
    python_abi-3.11            |          2_cp311           5 KB  conda-forge
    zlib-1.2.13                |       hd590300_5          91 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        51.5 MB

The following NEW packages will be INSTALLED:

  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5 
  llvm-openmp        conda-forge/linux-64::llvm-openmp-16.0.6-h4dfa4b3_0 
  mamba              conda-forge/linux-64::mamba-1.5.1-py311h3072747_0 
  python_abi         conda-forge/linux-64::python_abi-3.11-2_cp311 

The following packages will be REMOVED:

  libgomp-11.2.0-h1234567_1

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2023.05.30~ --> conda-forge::ca-certificates-2023.7.22-hbcca054_0 
  certifi            pkgs/main/linux-64::certifi-2023.5.7-~ --> conda-forge/noarch::certifi-2023.7.22-pyhd8ed1ab_0 
  conda              pkgs/main::conda-23.5.2-py311h06a4308~ --> conda-forge::conda-23.7.4-py311h38be061_0 
  fmt                       pkgs/main::fmt-9.1.0-hdb19cb5_0 --> conda-forge::fmt-10.1.1-h00ab1b0_0 
  libcurl                                  8.1.1-h251f7ec_1 --> 8.2.1-h251f7ec_0 
  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-13.2.0-h807b86a_2 
  libmamba             pkgs/main::libmamba-1.4.1-h2dafd23_1 --> conda-forge::libmamba-1.5.1-h744094f_0 
  libmambapy         pkgs/main::libmambapy-1.4.1-py311h2da~ --> conda-forge::libmambapy-1.5.1-py311hf2555c7_0 
  libsolv              pkgs/main::libsolv-0.7.22-he621ea3_0 --> conda-forge::libsolv-0.7.24-hfc55251_4 
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-13.2.0-h7e041cc_2 
  openssl               pkgs/main::openssl-3.0.9-h7f8727e_0 --> conda-forge::openssl-3.1.3-hd590300_0 
  zlib                    pkgs/main::zlib-1.2.13-h5eee18b_0 --> conda-forge::zlib-1.2.13-hd590300_5 

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_kmp_llvm 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                   
Preparing transaction: done                                                                                        
Verifying transaction: done                                                                                        
Executing transaction: done                              
```

Then ran the actual example

```
(base) root@412d20407f47:/# time mamba create -n test -c conda-forge numpy --dry-run
Traceback (most recent call last):
  File "/opt/conda/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory

real	0m0.453s
user	0m0.390s
sys	0m0.063s
```

### Conda Info

```shell
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.13: cannot open shared object file: No such file or directory)

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=6.1.41=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.11.4 Linux/6.1.41 debian/11 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.13: cannot open shared object file: No such file or directory)
==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.13: cannot open shared object file: No such file or directory)
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
boltons                   23.0.0          py311h06a4308_0    defaults
brotlipy                  0.7.0           py311h5eee18b_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.0               h5eee18b_0    defaults
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.7.4          py311h38be061_0    conda-forge
conda-content-trust       0.1.3           py311h06a4308_0    defaults
conda-libmamba-solver     23.5.0          py311h06a4308_0    defaults
conda-package-handling    2.1.0           py311h06a4308_0    defaults
conda-package-streaming   0.8.0           py311h06a4308_0    defaults
cryptography              39.0.1          py311h9ce1e76_2    defaults
fmt                       10.1.1               h00ab1b0_0    conda-forge
icu                       58.2                 he6710b0_3    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcurl                   8.2.1                h251f7ec_0    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libmamba                  1.5.1                h744094f_0    conda-forge
libmambapy                1.5.1           py311hf2555c7_0    conda-forge
libnghttp2                1.52.0               h2d74bed_1    defaults
libsolv                   0.7.24               hfc55251_4    conda-forge
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.3               hcbfbd50_0    defaults
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0    defaults
mamba                     1.5.1           py311h3072747_0    conda-forge
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.1.3                hd590300_0    conda-forge
packaging                 23.0            py311h06a4308_0    defaults
pcre2                     10.37                he7ceb23_1    defaults
pip                       23.1.2          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.4           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.4               h955ad1f_0    defaults
python_abi                3.11                    2_cp311    conda-forge
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.29.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                67.8.0          py311h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py311h06a4308_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311h06a4308_0    defaults
wheel                     0.38.4          py311h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml-cpp                  0.7.0                h295c915_1    defaults
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by costrouc** [comment]
Fixed it via

```
(base) root@412d20407f47:/# conda install -c conda-forge libarchive
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.13: cannot open shared object file: No such file or directory)
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - libarchive


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libarchive-3.6.2           |       h3d51595_0         816 KB  conda-forge
    lzo-2.10                   |    h516909a_1000         314 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.1 MB

The following NEW packages will be INSTALLED:

  lzo                conda-forge/linux-64::lzo-2.10-h516909a_1000 

The following packages will be SUPERSEDED by a higher-priority channel:

  libarchive         pkgs/main::libarchive-3.6.2-h6ac8c49_2 --> conda-forge::libarchive-3.6.2-h3d51595_0 


Proceed ([y]/n)? y
```

So I think that this is just an expected issue on conda of mixing defaults <-> conda-forge.
