### ISSUE TITLE
Uncaptured pinning error in conda-libmamba-solver in win-64

### ISSUE THREAD

**Issue by costrouc** [conda/conda-libmamba-solver#300]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

```
$ conda create -n pins python=3.10
$ conda activate pins
$ echo numpy >> $CONDA_PREFIX\conda-prefix\pinned
$ echo scipy=24 >> $CONDA_PREFIX\conda-prefix\pinned
$ conda install scipy --dry-run
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\cli\main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\cli\conda_argparse.py", line 167, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\notices\core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\cli\main_install.py", line 26, in execute
        install(args, parser, "install")
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\cli\install.py", line 316, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\core\solve.py", line 154, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\Miniconda3\Lib\site-packages\conda\core\solve.py", line 215, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\p\conda-libmamba-solver\conda_libmamba_solver\solver.py", line 213, in solve_final_state
        out_state = self._solving_loop(in_state, out_state, index)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\p\conda-libmamba-solver\conda_libmamba_solver\solver.py", line 265, in _solving_loop
        solved = self._solve_attempt(in_state, out_state, index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\chris\p\conda-libmamba-solver\conda_libmamba_solver\solver.py", line 370, in _solve_attempt
        self.solver.add_pin(spec)
    RuntimeError: No package can be installed for pin: scipy=24

`$ C:\Users\chris\Miniconda3\Scripts\conda-script.py install scipy --dry-run`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_BAT=C:\Users\chris\Miniconda3\condabin\conda.bat
        CONDA_DEFAULT_ENV=pins1
                CONDA_EXE=C:\Users\chris\Miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\chris\Miniconda3\envs\pins1
           CONDA_PREFIX_1=C:\Users\chris\Miniconda3
    CONDA_PROMPT_MODIFIER=(pins1)
         CONDA_PYTHON_EXE=C:\Users\chris\Miniconda3\python.exe
               CONDA_ROOT=C:\Users\chris\Miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\chris
               LD_PRELOAD=<not set>
                     PATH=C:\Users\chris\Miniconda3\envs\pins1;C:\Users\chris\Miniconda3\envs\pi
                          ns1\Library\mingw-
                          w64\bin;C:\Users\chris\Miniconda3\envs\pins1\Library\usr\bin;C:\Users\
                          chris\Miniconda3\envs\pins1\Library\bin;C:\Users\chris\Miniconda3\envs
                          \pins1\Scripts;C:\Users\chris\Miniconda3\envs\pins1\bin;c:\Users\chris
                          \.vscode-
                          server\bin\2ccd690cbff1569e4a83d7c43d45101f817401dc\bin\remote-cli;C:\
                          Users\chris\Miniconda3\condabin;C:\Windows\system32;C:\Windows;C:\Wind
                          ows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Window
                          s\System32\OpenSSH;C:\Program Files\Tailscale;C:\Program Files\Git\cmd
                          ;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\Wind
                          owsApps;C:\Users\chris\AppData\Local\pixi\bin;C:\Users\chris\AppData\L
                          ocal\Microsoft\WindowsApps;C:\Users\chris\AppData\Local\Programs\Micro
                          soft VS Code\bin;C:\Users\chris\AppData\Local\GitHubDesktop\bin;C:\Use
                          rs\chris\.dotnet\tools
             PSMODULEPATH=C:\Users\chris\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program
                          Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\
                          v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=C:\Users\chris\Miniconda3\envs\pins1\Library\ssl\cacert.pem

     active environment : pins1
    active env location : C:\Users\chris\Miniconda3\envs\pins1
            shell level : 2
       user config file : C:\Users\chris\.condarc
 populated config files : C:\Users\chris\.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\chris\Miniconda3  (writable)
      conda av data dir : C:\Users\chris\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\chris\Miniconda3\pkgs
                          C:\Users\chris\.conda\pkgs
                          C:\Users\chris\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\chris\Miniconda3\envs
                          C:\Users\chris\.conda\envs
                          C:\Users\chris\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.11.4 Windows/10 Windows/10.0.22621 solver/libmamba conda-libmamba-solver/23.7.1.dev20+g4a53423 libmambapy/1.4.1
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
```

### Conda Info

```shell
active environment : pins1
    active env location : C:\Users\chris\Miniconda3\envs\pins1
            shell level : 2
       user config file : C:\Users\chris\.condarc
 populated config files : C:\Users\chris\.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\chris\Miniconda3  (writable)
      conda av data dir : C:\Users\chris\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\chris\Miniconda3\pkgs
                          C:\Users\chris\.conda\pkgs
                          C:\Users\chris\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\chris\Miniconda3\envs
                          C:\Users\chris\.conda\envs
                          C:\Users\chris\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.11.4 Windows/10 Windows/10.0.22621 solver/libmamba conda-libmamba-solver/23.7.1.dev20+g4a53423 libmambapy/1.4.1
          administrator : True
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\chris\.condarc <==
solver: libmamba

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
# packages in environment at C:\Users\chris\Miniconda3\envs\pins1:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.08.22           haa95532_0    defaults
libffi                    3.4.4                hd77b12b_0    defaults
openssl                   3.0.11               h2bbff1b_2    defaults
pip                       23.2.1          py310haa95532_0    defaults
python                    3.10.13              he1021f5_0    defaults
setuptools                68.0.0          py310haa95532_0    defaults
sqlite                    3.41.2               h2bbff1b_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.41.2          py310haa95532_0    defaults
xz                        5.4.2                h8cc25b3_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
```

### Additional Context

This is using libmamba 1.4.1 so unsure if this is worth a bug report.

**Comment by jaimergp** [comment]
If you can't reproduce this with libmamba 1.5.1, then it's not worth the trouble because that will be our minimum version requirement.

**Comment by jaimergp** [comment]
This is for reference the friendlier error you get with libmamba 1.5.1:

```
test_user@bd45fee6fab7:/opt/conda-src$ conda create -n pins python=3.11
Channels:
 - defaults
Platform: linux-aarch64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/test_user/.conda/envs/pins

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-3.0.11             |       h2f4d8fa_2         5.3 MB
    python-3.11.5              |       h4bb2201_0        15.4 MB
    ------------------------------------------------------------
                                           Total:        20.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-aarch64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-aarch64::_openmp_mutex-5.1-51_gnu 
  bzip2              pkgs/main/linux-aarch64::bzip2-1.0.8-hfd63f10_2 
  ca-certificates    pkgs/main/linux-aarch64::ca-certificates-2023.08.22-hd43f75c_0 
  ld_impl_linux-aar~ pkgs/main/linux-aarch64::ld_impl_linux-aarch64-2.38-h8131f2d_1 
  libffi             pkgs/main/linux-aarch64::libffi-3.4.4-h419075a_0 
  libgcc-ng          pkgs/main/linux-aarch64::libgcc-ng-11.2.0-h1234567_1 
  libgomp            pkgs/main/linux-aarch64::libgomp-11.2.0-h1234567_1 
  libstdcxx-ng       pkgs/main/linux-aarch64::libstdcxx-ng-11.2.0-h1234567_1 
  libuuid            pkgs/main/linux-aarch64::libuuid-1.41.5-h998d150_0 
  ncurses            pkgs/main/linux-aarch64::ncurses-6.4-h419075a_0 
  openssl            pkgs/main/linux-aarch64::openssl-3.0.11-h2f4d8fa_2 
  pip                pkgs/main/linux-aarch64::pip-23.2.1-py311hd43f75c_0 
  python             pkgs/main/linux-aarch64::python-3.11.5-h4bb2201_0 
  readline           pkgs/main/linux-aarch64::readline-8.2-h998d150_0 
  setuptools         pkgs/main/linux-aarch64::setuptools-68.0.0-py311hd43f75c_0 
  sqlite             pkgs/main/linux-aarch64::sqlite-3.41.2-h998d150_0 
  tk                 pkgs/main/linux-aarch64::tk-8.6.12-h241ca14_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  wheel              pkgs/main/linux-aarch64::wheel-0.41.2-py311hd43f75c_0 
  xz                 pkgs/main/linux-aarch64::xz-5.4.2-h998d150_0 
  zlib               pkgs/main/linux-aarch64::zlib-1.2.13-h998d150_0 


Proceed ([y]/n)? 


Downloading and Extracting Packages
                                                                                                          
Preparing transaction: done                                                                               
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pins
#
# To deactivate an active environment, use
#
#     $ conda deactivate
(base) test_user@bd45fee6fab7:/opt/conda-src$ conda activate pins
(pins) test_user@bd45fee6fab7:/opt/conda-src$ echo "scipy=24" > $CONDA_PREFIX/conda-meta/pinned
(pins) test_user@bd45fee6fab7:/opt/conda-src$ conda install scipy
Channels:
 - defaults
Platform: linux-aarch64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - scipy=24

Current channels:

  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
