### ISSUE TITLE
Libmamba solver appears to be trying to use previously configured channel

### ISSUE THREAD

**Issue by DManowitz** [conda/conda-libmamba-solver#489]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I tried to install the `motor=3.5.1` package, but got the following result:

```
conda install motor=3.5.1
Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (C:\Users\manow\miniconda3\lib\site-packages\conda\plugins\types.py))
Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (C:\Users\manow\miniconda3\lib\site-packages\conda\plugins\types.py))
Channels:
 - pytorch
 - pyg
 - nvidia/label/cuda-11.3.1
 - conda-forge
 - https://software.repos.intel.com/python/conda
 - defaults
 - intel
Platform: win-64
Collecting package metadata (repodata.json): - ERROR conda.auxlib.logz:stringify(171): Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\manow\miniconda3\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\manow\miniconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\manow\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\manow\miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manow\miniconda3\lib\site-packages\conda\auxlib\logz.py", line 165, in stringify
    requests_models_Response_builder(builder, obj)
  File "C:\Users\manow\miniconda3\lib\site-packages\conda\auxlib\logz.py", line 141, in requests_models_Response_builder
    resp = response_object.json()
  File "C:\Users\manow\miniconda3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR conda.auxlib.logz:stringify(171): Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\manow\miniconda3\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\manow\miniconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\manow\miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\manow\miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\manow\miniconda3\lib\site-packages\conda\auxlib\logz.py", line 165, in stringify
    requests_models_Response_builder(builder, obj)
  File "C:\Users\manow\miniconda3\lib\site-packages\conda\auxlib\logz.py", line 141, in requests_models_Response_builder
    resp = response_object.json()
  File "C:\Users\manow\miniconda3\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.
```

I know that the `intel` channel on `conda.anaconda.org` is no longer valid, and I have removed it from my `.condarc` file.  However, when I try to install this package using the libmamba solver, it somehow adds the `intel` channel to the channels that I currently have configured.  When I am not using the libmamba solver, it does not do this.

### Conda Info

```shell
active environment : py37_ml_TfGpuMain
    active env location : C:\Users\manow\miniconda3\envs\py37_ml_TfGpuMain
            shell level : 1
       user config file : C:\Users\manow\.condarc
 populated config files : C:\Users\manow\.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.5=0
                          __win=0=0
       base environment : C:\Users\manow\miniconda3  (writable)
      conda av data dir : C:\Users\manow\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/pyg/win-64
                          https://conda.anaconda.org/pyg/noarch
                          https://conda.anaconda.org/nvidia/label/cuda-11.3.1/win-64
                          https://conda.anaconda.org/nvidia/label/cuda-11.3.1/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://software.repos.intel.com/python/conda/win-64
                          https://software.repos.intel.com/python/conda/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\manow\miniconda3\pkgs
                          C:\Users\manow\.conda\pkgs
                          C:\Users\manow\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\manow\miniconda3\envs
                          C:\Users\manow\.conda\envs
                          C:\Users\manow\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.28.1 CPython/3.10.12 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/23.7.0 libmambapy/1.4.7 aau/0.4.4 c/. s/. e/.
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\manow\.condarc <==
pip_interop_enabled: True
channel_priority: disabled
channels:
  - pytorch
  - pyg
  - nvidia/label/cuda-11.3.1
  - conda-forge
  - https://software.repos.intel.com/python/conda/
  - defaults
solver: libmamba

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
Can send separately if needed.  Adding gives Github error: comment too long.
```

**Comment by jaimergp** [comment]
From 23.9.0 on, conda-libmamba-solver won't try to use channels that are unavailable. I'd recommend to upgrade. To prevent the error, you can set [this environment variable](https://conda.github.io/conda-libmamba-solver/user-guide/configuration/#advanced-options): `CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1`.

**Comment by jaimergp** [comment]
Sorry, that's a typo. You need conda-libmamba-solver 24.11 or later.

**Comment by jaimergp** [comment]
That key is an environment variable btw, not a setting. It should work with 24.9 and earlier.

**Comment by rootsmusic** [comment]
>To prevent the error, you can set [this environment variable](https://conda.github.io/conda-libmamba-solver/user-guide/configuration/#advanced-options): `CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1`.

Sorry @jaimergp, I'm a beginner with conda.  I looked at the linked user guide, but it doesn't have instructions to configure conda's special environment variables.  How can I set that key?  Thanks.

**Comment by jaimergp** [comment]
It's a regular shell environment variable. 

- In Linux or macOS: `export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1`
- Windows: `set CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1`

It will be valid only in the current terminal session. I'd set it, upgrade to conda-libmamba-solver 24.11 and then it should be fixed.
