### ISSUE TITLE
Stacktrace Shown rather than standard error message when libmamba gets HTTP 404

### ISSUE THREAD

**Issue by remkade** [conda/conda-libmamba-solver#68]

**Comment by jezdez** [comment]
This will probably fixed by #65

**Comment by AlbertDeFusco** [comment]
Could my problem be related or should I open another ticket?

I get a JSON serialization error when libmamba fails with with the `--json` filag.
* conda 23.1.0
* conda-libmamba-solver 23.1.0
* libmamba 1.3.1
* libmambapy 1.3.1

I'm fairly certain that I was not having this problem 2 - 3 months ago on earlier versions of conda and libmamba.

```
❯ CONDA_SOLVER=libmamba conda create -n t -c conda-forge conda-token --json --override-channels
Traceback (most recent call last):
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1124, in __call__
    return func(*args, **kwargs)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 69, in main_subshell
    exit_code = do_call(args, p)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 280, in install
    raise e
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 264, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 132, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 175, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 188, in solve_final_state
    out_state = self._solving_loop(in_state, out_state, index)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 251, in _solving_loop
    solved = self._solve_attempt(in_state, out_state, index)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 325, in _solve_attempt
    new_conflicts = self._problems_to_specs(problems, old_conflicts)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 571, in _problems_to_specs
    self._raise_for_problems(problems)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 597, in _raise_for_problems
    raise exc
conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

  - conda-token

Current channels:

  - https://conda.anaconda.org/conda-forge

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adefusco/Applications/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1424, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1127, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1156, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1170, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1174, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1097, in print_conda_exception
    exc_json = json.dumps(exc_val.dump_map(), indent=2, sort_keys=True, cls=EntityEncoder)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/auxlib/entity.py", line 962, in default
    return JSONEncoder.default(self, obj)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/site-packages/conda/__init__.py", line 145, in _default
    return getattr(obj.__class__, "to_json", _default.default)(obj)
  File "/Users/adefusco/Applications/miniconda3/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IndexedSet is not JSON serializable
```

With the classic solver I get clean json

```
❯ CONDA_SOLVER=classic conda create -n t -c conda-forge conda-token --json --override-channels
{
  "caused_by": "None",
  "channel_urls": [
    "https://conda.anaconda.org/conda-forge/osx-arm64",
    "https://conda.anaconda.org/conda-forge/noarch"
  ],
  "channels_formatted": "  - https://conda.anaconda.org/conda-forge/osx-arm64\n  - https://conda.anaconda.org/conda-forge/noarch",
  "error": "PackagesNotFoundError: The following packages are not available from current channels:\n\n  - conda-token\n\nCurrent channels:\n\n  - https://conda.anaconda.org/conda-forge/osx-arm64\n  - https://conda.anaconda.org/conda-forge/noarch\n\nTo search for alternate channels that may provide the conda package you're\nlooking for, navigate to\n\n    https://anaconda.org\n\nand use the search bar at the top of the page.\n",
  "exception_name": "PackagesNotFoundError",
  "exception_type": "<class 'conda.exceptions.PackagesNotFoundError'>",
  "message": "The following packages are not available from current channels:\n\n  - conda-token\n\nCurrent channels:\n\n  - https://conda.anaconda.org/conda-forge/osx-arm64\n  - https://conda.anaconda.org/conda-forge/noarch\n\nTo search for alternate channels that may provide the conda package you're\nlooking for, navigate to\n\n    https://anaconda.org\n\nand use the search bar at the top of the page.\n",
  "packages": [
    "conda-token"
  ],
  "packages_formatted": "  - conda-token"
}
```

**Comment by jaimergp** [comment]
Different problem, but thanks for the report! See #140 @AlbertDeFusco
